name = "SomeStructuredMatrices"
uuid = "459f034e-b58d-4944-8db1-0e38c8b93194"
authors = ["Jenifer De Jager (jraind@vt.edu) and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
LinearAlgebra = "1"
Test = "1"
Aqua = "~0.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
